baseURL = '/'
defaultContentLanguage = "en-us"
languageCode = "en-us"
title = 'Scott Ginn'
disableHugoGeneratorInject = false
PygmentsCodeFences = false
PygmentsStyle = "none"
pluralizelisttitles = "false"
enableRobotsTXT = true
enableEmoji = false
disableKinds = ['taxonomy', 'term', 'sitemap']

[params]
favicon = "icon.png"
