[build]
publish = "public"
command = "npm run build:hugo"

[build.environment]
GO_VERSION = "1.19"
HUGO_VERSION = "0.104.3"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"
WC_POST_CSS = "true"
SHOGINN_SCRIPTS_HUGO_BASE_URL = "$URL"

[context.deploy-preview]
SHOGINN_SCRIPTS_HUGO_BASE_URL = "$DEPLOY_PRIME_URL"
HUGO_BUILDFUTURE = "true"

[context.branch-deploy]
SHOGINN_SCRIPTS_HUGO_BASE_URL = "$DEPLOY_PRIME_URL"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"

[plugins.inputs]
debug = true
